[package]
name = "rustle"
version = "0.1.0"
author = ["Niko Abeler <niko@rerere.org>"]
license = "MIT"
description = "A Wordle clone for the command line"
readme = "README.md"
homepage = "https://github.com/H4kor/rustle"
repository = "https://github.com/H4kor/rustle"
keywords = ["cli", "game", "wordle"]
categories = ["games"]

edition = "2021"

[dependencies]
termion = "*"
rand = "*"